# Generated by Django 4.2.6 on 2023-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('left_key', models.IntegerField()),
                ('right_key', models.IntegerField()),
            ],
        ),
    ]
