# Generated by Django 4.2.6 on 2023-10-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nested_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
